#ifndef _DATA_H_
#define _DATA_H_

extern struct {
	int num;
	unsigned int start;
	unsigned int end;
} frags[];

enum gamemode_e {
	GAMEMODE_TITLE = 1,
	GAMEMODE_MAINSELECT,
	GAMEMODE_WHITECITY,
	GAMEMODE_GBEMU,
	GAMEMODE_OAKSLAB,
	GAMEMODE_CLASS,
	GAMEMODE_BEDROOM,
	GAMEMODE_CASTLE,
	GAMEMODE_MINIGAMES,
	GAMEMODE_OPTIONS,
	GAMEMODE_CRASH12,
	GAMEMODE_EVENTBATTLE,
	GAMEMODE_BATTLENOW,
	GAMEMODE_VSRIVAL,
	GAMEMODE_FREEBATTLE,
	GAMEMODE_INIT,
	GAMEMODE_MAINSELECT18,
	GAMEMODE_MYSTERYGIFT,
	GAMEMODE_GBSL
};


#endif
